### ISSUE TITLE
Version 2.0.0 won't start

### ISSUE THREAD

**Issue by marhoy** [hassio-addons/addon-homebridge#41] opened 2017-10-22 07:04 UTC
After upgrading to version 2.0.0, the add-on won't start. Do I need to refresh or reset something? Have tried to uninstall/install and to reboot the host.

The log contains the following:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-homebridge: applying... 
[fix-attrs.d] 10-homebridge: exited 0.
[fix-attrs.d] 20-dbus: applying... 
[fix-attrs.d] 20-dbus: exited 0.
[fix-attrs.d] 30-avahi: applying... 
[fix-attrs.d] 30-avahi: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[06:59:33+0000] ERROR ----> Something went wrong contacting the API
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
**ERROR: Something went wrong contacting the API**
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 20-dbus.sh: executing... 
[cont-init.d] 20-dbus.sh: exited 0.
[cont-init.d] 30-avahi.sh: executing... 
ERROR: Something went wrong contacting the API
[cont-init.d] 30-avahi.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by andyrooo82** [comment] 2017-10-22 07:06
I’ve just this minute upgraded to version 2.0.0 and I’m getting the exact above issue. Tried restarting plugin but this didn’t resolve the issue.

**Comment by codepilotnl** [comment] 2017-10-22 09:24
Also getting this issue, after a fresh install of homebridge no upgrade.

**Comment by frenck** [comment] 2017-10-22 10:18
Duplicate of #40.
Please check the refered issue for more details, maybe you could help provide me more details in #40.

**Closed as completed by frenck** 2017-10-22 10:18 UTC
