### ISSUE TITLE
How-to: Logs?

### ISSUE THREAD

**Issue by CroVlado** [hassio-addons/addon-homebridge#81] opened 2018-03-03 04:31 UTC
Is there a way to output logs into a console accessible via samba or one that shows all the logs and doesn’t disappear half of it?
Maybe something similar to the homebridge.log file that’s in the config folder?
Sitting in homebridge add on trying to trouble shoot issues having to spam the refresh button gets annoying.

**Comment by frenck** [comment] 2018-03-05 05:51
I agree!
This is a general Hass.io add-on problem. Maybe we could solve this on Hass.io level.
I might suggest this to @pvizeli...

**Comment by frenck** [comment] 2018-03-17 20:58
Closing this issue, since it is not a bug and/or limitation of this add-on.

**Closed as completed by frenck** 2018-03-17 20:58 UTC
