### ISSUE TITLE
Automatic restart needed

### ISSUE THREAD

**Issue by marhoy** [hassio-addons/addon-homebridge#16] opened 2017-09-15 14:21 UTC
## Problem/Motivation
Homebridge seems to die from time to time (don't know where to find the log, so I don't know the reason). But this is not deteced, so the hassio add-on is justed "stopped" and must be "started" again manually.

## Expected behavior
Since I have selected Boot -> Auto, I expect the process to be automatically restarted if it dies. As I would from any other system daemon.

## Actual behavior
The Homebridge add-on does not automatically start homebridge again if it dies.

## Steps to reproduce
Just keep the add-on running for some days, and it will eventually die. I am using the homebridge-harmonyhub in addition to the standard configuration.

## Proposed changes
Make the Homebridge add-on automatically start homebridge again if it dies.

**Comment by frenck** [comment] 2017-09-15 20:21
I'm aware of this problem. This is actually limited by design of the Hass.io base images and design of container use.

Currently working on a replacement for this.

**Comment by WEZANGO** [comment] 2017-09-16 09:54
Or maybe it can at least cache devices so we should not rename devices, change icons and create scenes in home app every time it restarts.

**Comment by frenck** [comment] 2017-09-16 10:04
@WEZANGO I don't see how this is related to the issue reported. The behavior you describe sounds like an issue with Homebridge itself, not the add-on.

**Comment by WEZANGO** [comment] 2017-09-16 10:31
I thought it was because of restart problem. Then I will report another issue. Thanks

**Comment by frenck** [comment] 2017-10-11 20:53
Added this issue to a larger project, that adds a proper process management to this add-on.

**Comment by frenck** [comment] 2017-10-21 19:45
This issue is partially fixed in v2.0.0 of the add-on since it introduces a process manager.
Nevertheless, if something goes wrong, the add-on will die. This is how Docker is designed. These causes should be handled by the Hass.io platform, not by the add-on themselves.

**Closed as completed by frenck** 2017-10-21 19:45 UTC
